js/lang/fr.js
1. The later is a more natural French expression.  You may compare GitHub's code search results for the [former](https://github.com/search?q=%22ouvrir+un+numéro%22&type=Code) and the [later](https://github.com/search?q=%22ouvrir+un+ticket%22&type=Code).
2. French colons are surrounded with spaces.
3. I wonder if you have the possibility to change line 16 to "Conditions générales d'utilisation", or simply "[CGU](https://fr.wikipedia.org/wiki/Conditions_g%C3%A9n%C3%A9rales_d%27utilisation)".  Every native French speaker will understand what it means.
https://github.com/daisy/kb/blob/e56359ae8e8ce94f93456ec658e93d99ee91790d/js/lang/fr.js#L16
=> Meilleures traductions

publishing/docs/metadata/schema.org/accessMode.html, publishing/docs/metadata/schema.org/accessModeSufficient.html, publishing/docs/metadata/schema.org/accessibilityFeature.html, publishing/docs/metadata/schema.org/accessibilityHazard.html
Fixes #30:
- expands examples for accessMode, accessibilityFeature, and accessibilityHazard to show more than one value for the most pertinent formats
- adds a note about how to deal with multiple values to the above three and accessModeSufficient
=> update schema.org metadata examples to show multiple values

publishing/docs/html/notes.html
Example 4 on the [Notes](http://kb.daisy.org/publishing/docs/html/notes.html) page appears to have an incorrect close tag. This PR fixes that.
=> fix typo in notes example 4

publishing/docs/html/dropcaps.html
The example in the [drop cap page](http://kb.daisy.org/publishing/docs/html/dropcaps.html) shows
```CSS
section[@role='doc-chapter'] p:first-child {
initial-letter: 2.0;
}
```
And there's a note:
> (Note that an integer value like "2.0" creates a drop cap, while a whole number like "2" would create a raised cap.)
This is not correct. The initial-letter property takes [two values](https://drafts.csswg.org/css-inline-3/#sizing-drop-initials): the first is the size of the drop cap, and the second is how many lines the drop cap sinks. `initial-letter: 2` is interpreted as `initial-letter: 2 2` which creates a two-line drop cap. It doesn't matter if the value is `2` or `2.0`. To create a raised cap you would use `initial-letter: 2 1`.
=> Correction for CSS initial-letter property

publishing/docs/html/lists.html
Hi, discovered some errors in the MDN links on the KB page on lists, this PR fixes them.
=> Fixing incorrect links to MDN on list page

publishing/docs/epub/language.html
An xml:lang must be specified on each metadata element.
=> Note that epub 2 does not allow language declarations on the package element

js/topics/en.js, publishing/docs/navigation/pagebreaks.html, publishing/docs/navigation/pagelist.html, publishing/docs/navigation/pagenav.html, publishing/docs/navigation/pagesrc.html, publishing/docs/new/feed.xml
Having a single page to cover all three topics was becoming unwieldy. This pull request breaks out page break markers, page list, and page source identification and adds a separate overview to cover how they relate to each other.
It also expands the frequently asked questions to cover a number of issues that have been raised recently, such as not putting page breaks in headings, how to identify the source if it lacks a unique identifier, giving preference to `pageBreakSource`, etc.
=> Split the page navigation page into separate topics

js/topics/en.js, publishing/docs/epub/validation/index.html
Fixes the id to search for so the full list of epub topics doesn't appear, and removes the old hard-coded links from the index.html file.
Fixes #80
=> Fix validation topics index

publishing/docs/navigation/pagebreaks.html
Discovered a typo in the KB, on the "Page Break Markers" page, here is a fix.
=> Fix typo in code example

css/kb.css, js/details.js, js/init.js, js/lang/en/sc.json, publishing/docs/epub/validation/ace.html, publishing/docs/epub/validation/smart.html, publishing/docs/metadata/schema.org/accessibilityFeature.html, publishing/docs/wcag/accessible-authentication-no-exception.html, publishing/docs/wcag/accessible-authentication.html, publishing/docs/wcag/contrast-enhanced.html, publishing/docs/wcag/contrast-minimum.html, publishing/docs/wcag/index.html, publishing/docs/wcag/motion-actuation.html, publishing/docs/wcag/non-text-content.html, publishing/docs/wcag/target-size-enhanced.html, publishing/docs/wcag/target-size-minimum.html
This pull request fixes the following issues:
- it fixes the numbering and title changes that occurred WCAG 2.2 that were missed
- it adds the new WCAG 2.2 SC to the sc.json file (for transforming technique references)
- it removes a duplicate entry for ttsMarkup from the accessibility features list
- it adds mention of epubcheck being available in Japanese and links to the transifex project so people can look up current support
- it moves the code to replace details elements with div/button equivalents to the init script (to work around the translation problems the element is causing)
=> Various minor fixes

publishing/docs/metadata/schema.org/accessibilityFeature/MathML.html, publishing/docs/metadata/schema.org/accessibilityFeature/alternativeText.html, publishing/docs/metadata/schema.org/accessibilityFeature/longDescription.html, publishing/docs/metadata/schema.org/accessibilityFeature/pageBreakMarkers.html, publishing/docs/metadata/schema.org/accessibilityFeature/pageNavigation.html, publishing/docs/metadata/schema.org/accessibilityFeature/readingOrder.html, publishing/docs/metadata/schema.org/accessibilityFeature/structuralNavigation.html, publishing/docs/metadata/schema.org/accessibilityFeature/synchronizedAudioText.html, publishing/docs/metadata/schema.org/accessibilityFeature/tableOfContents.html, publishing/docs/metadata/schema.org/accessibilityFeature/ttsMarkup.html
When the accessibility feature pages were split out and moved down a folder, some of the links out to other KB pages broke. This PR adds an extra "../" to the broken paths so they'll work again.
=> Fix broken links

publishing/docs/navigation/pagebreaks.html
The functionality described usually comes through the page list, so the support statement just added unnecessary confusion. Better to remove it and note the need for both.
=> Remove support note for page breaks

publishing/docs/html/dpub-aria/doc-abstract.html, publishing/docs/html/dpub-aria/doc-backlink.html, publishing/docs/html/dpub-aria/doc-biblioref.html, publishing/docs/html/dpub-aria/doc-colophon.html, publishing/docs/html/dpub-aria/doc-cover.html, publishing/docs/html/dpub-aria/doc-credit.html, publishing/docs/html/dpub-aria/doc-dedication.html, publishing/docs/html/dpub-aria/doc-endnote.html, publishing/docs/html/dpub-aria/doc-epigraph.html, publishing/docs/html/dpub-aria/doc-example.html, publishing/docs/html/dpub-aria/doc-footnote.html, publishing/docs/html/dpub-aria/doc-glossref.html, publishing/docs/html/dpub-aria/doc-noteref.html, publishing/docs/html/dpub-aria/doc-notice.html, publishing/docs/html/dpub-aria/doc-pagebreak.html, publishing/docs/html/dpub-aria/doc-pullquote.html, publishing/docs/html/dpub-aria/doc-qna.html, publishing/docs/html/dpub-aria/doc-subtitle.html, publishing/docs/html/dpub-aria/doc-tip.html
Fixes the copy/paste addition of a grammatically incorrect "a" from the role inheritance sections.
=> Fix "the a" typo

publishing/docs/metadata/onix.html
This pull request clarifies that the preference for semantic mathml is the onix definition.
=> Clarify the quoted definition comes from onix

publishing/docs/html/iframes.html, publishing/docs/html/links.html, publishing/docs/html/maps.html
Fixes two typos and clarifies the advice on scrolling iframes so it is not mistaken as about the obsolete `scrolling` attribute.
=> Fix issues identified in translation

publishing/docs/html/title.html
=> Switch "do" to "do not" for reusing publication title as each html document title

publishing/docs/contribute/index.html
Switches "topic" to "category" for the page metadata. Removes a reference to "topic" where it's easy to confuse with setting the category.
=> Fix uses of "topic"

js/init.js
Improves the custom search results for Japanese but we might still need to create a separate search engine for the translation as it appears there are interface components that can only be localized to the language in the control panel.
=> Localize searching

css/kb.css
Prevent wrapped words from being too close together.
=> Increase line height for topic headings

publishing/docs/html/images-desc.html, publishing/docs/new/feed.xml, publishing/docs/new/index.html
This pull request moves the technique for using a hyperlink to link to the description ahead of the details element. It also adds aria-details to the example.
=> Update priority of extended description mechanisms
